[package]
name = "skyflake"
version = "0.0.1-alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datafusion = "7.0.0"
tokio = { version = "1.15.0", features = ["full"] }
linefeed = "0.6"